-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 30, 2024 at 09:32 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ecogensphere`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_users`
--

CREATE TABLE `admin_users` (
  `id` int(11) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `crop_library`
--

CREATE TABLE `crop_library` (
  `id` text DEFAULT NULL,
  `plant_name` text DEFAULT NULL,
  `scientific_name` text DEFAULT NULL,
  `family` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `varieties` text DEFAULT NULL,
  `soil_and_climate` text DEFAULT NULL,
  `planting_material` text DEFAULT NULL,
  `field_preparation` text DEFAULT NULL,
  `irrigation` text DEFAULT NULL,
  `manures_and_fertilizers` text DEFAULT NULL,
  `after_cultivation` text DEFAULT NULL,
  `intercropping` text DEFAULT NULL,
  `harvest` text DEFAULT NULL,
  `yield` text DEFAULT NULL,
  `pest_management` text DEFAULT NULL,
  `planting` text DEFAULT NULL,
  `spacing` text DEFAULT NULL,
  `canopy_management` text DEFAULT NULL,
  `top_working` text DEFAULT NULL,
  `growth_regulators` text DEFAULT NULL,
  `off_season_crop_induction` text DEFAULT NULL,
  `Season_of_Planting` text DEFAULT NULL,
  `Application_of_Fertilizers` text DEFAULT NULL,
  `Aftercultivation` text DEFAULT NULL,
  `Micronutrients` text DEFAULT NULL,
  `Special_Practices` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `crop_library`
--

INSERT INTO `crop_library` (`id`, `plant_name`, `scientific_name`, `family`, `image`, `varieties`, `soil_and_climate`, `planting_material`, `field_preparation`, `irrigation`, `manures_and_fertilizers`, `after_cultivation`, `intercropping`, `harvest`, `yield`, `pest_management`, `planting`, `spacing`, `canopy_management`, `top_working`, `growth_regulators`, `off_season_crop_induction`, `Season_of_Planting`, `Application_of_Fertilizers`, `Aftercultivation`, `Micronutrients`, `Special_Practices`) VALUES
('2', 'Banana', 'Musa spp.', 'Musaceae', 'banana.png', 'Rasbale', 'Sandy loam soils with good drainage are ideal. It can tolerate a pH range of 6.0 - 7.5.', 'Tissue culture plants or suckers', 'Dig pits of 60 cm x 60 cm x 60 cm size and fill it up with topsoil mixed with 10 kg of FYM and 100 g of neem cake. Plant the suckers at a spacing of 1.8 m x 1.8 m.', 'Immediately after planting and thereafter once in three days till establishment.', 'Apply 25 kg FYM, 100 g N, 40 g P2O5 and 140 g K2O per plant, three times a year in June, September and December.', 'Regular weeding and earthing up at 2 months interval.', 'Beans or bhendi can be grown as intercrop for the first 2 - 3 years.', '8 - 10 months after planting, 3 - 4 bunches/plant', 'Stem borer: Inserting a cloth wrapped stiff wire into the tunnel and killing the larva; Keep the field free from weeds and trash.', 'Planting is done in pits of 60 cm x 60 cm x 60 cm size filled with topsoil mixed with 10 kg of FYM and 100 g of neem cake.', 'Spacing of 1.8 m x 1.8 m is followed.', 'The planting material should be planted in rows with a spacing of 1.8 m between rows.', 'The top portion of the pseudostem can be cut and the leaves should be removed 15 days before planting.', 'Regular inspection and removal of male buds, dead flowers and old leaves.', 'First dose of fertilizer is applied three months after planting and the second dose six months after planting.', 'Removing the male buds and de-suckering are done after the bunch harvest.', 'After each harvest, the plant debris should be removed and destroyed.', 'Mulching with straw or dry leaves is done to conserve moisture and control weeds.', '', '', ''),
('3', 'Acid Lime', 'Citrus aurantifolia Swingle', 'Rutaceae', 'lemon.png', 'Local - Mexican lime', 'Requires well drained soils with a pH range of 5.5 - 7.5.', 'Budded plants or cuttings', 'Preparing pits of size 60 cm x 60 cm x 60 cm and filling them with 10 kg of FYM mixed with 500 g of neem cake. Planting the budded plants or cuttings at a spacing of 5 m x 5 m.', 'After planting, water the plants daily for the first 15 days, then once in 3 days till one month and thereafter, once in a week.', 'Apply FYM 25 kg, Neem cake 1 kg, Neem oil 200 ml, Azospirillum 500 g and Phosphobacteria 500 g per plant/year.', 'Remove the weeds and keep the basins weed free.', 'Short duration vegetables like radish, carrot, coriander, bhendi or beans can be grown as intercrops during the initial years.', '3 - 4 years after planting, The crop can be harvested 2 - 3 times a year.', 'Apply N, P and K at the rate of 500, 200 and 100 g per plant in June, October and February.', 'Provide one or two hoeing and weeding every year.', 'Apply lime and magnesium as per soil test recommendations.', 'Pruning should be done 2 - 3 times in a year to avoid overcrowding of branches and to remove water sprouts.', 'Off season flowering can be induced by applying 3% KNO3 solution at the rate of 50 ml/plant.', 'June – July and November – December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The application of micronutrients like zinc, copper, iron and manganese should be done based on soil and leaf analysis.', 'The soil in the basins should be worked to remove weeds and dead leaves, and to prevent water stagnation.', '', '', '', '', ''),
('4', 'Sweet Orange', 'Citrus sinensis (L.) Osbeck', 'Rutaceae', 'sweet-orange.png', 'Nucellar seedlings (Local - Khasi)', 'A well-drained, fertile soil with a pH range of 5.5 - 7.5 is ideal. The crop can tolerate slightly alkaline soils.', 'Budded plants', 'Dig pits of size 90 cm x 90 cm x 90 cm and fill them up with 15 kg of FYM and 500 g of neem cake. Plant the budded plants at a spacing of 7.5 m x 7.5 m.', 'For the first 15 days after planting, water the plants daily and then irrigate once in 3 days till one month and thereafter, irrigate once a week.', 'Apply FYM 50 kg, neem cake 2 kg, neem oil 400 ml, Azospirillum 1 kg and Phosphobacteria 1 kg per plant per year.', 'Keep the basin weed free and provide drainage.', 'Dhaincha or cowpea can be grown as intercrop during the initial years of planting.', 'The crop starts bearing 5 - 6 years after planting and the yield increases with the age of the plant.', 'Apply N, P and K at the rate of 600, 300 and 300 g per plant in June, September and January.', 'The soil around the basin should be worked to remove weeds and to facilitate aeration.', 'Apply zinc sulphate and magnesium sulphate at the rate of 50 g each per plant per year.', 'Regular pruning should be done to remove water sprouts, dead and diseased branches.', 'Flowering and fruiting can be induced by spraying 200 ppm Ethrel during December - January.', 'June - July and November - December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The micronutrients like zinc, copper, iron and manganese should be applied based on soil and leaf analysis.', 'A light irrigation should be given to the plants just before the onset of monsoon to facilitate uniform and better growth.', '', '', '', '', ''),
('5', 'Coconut', 'Cocos nucifera L.', 'Arecaceae', 'coconut.png', 'Tall, Dwarf, Hybrid varieties', 'Sandy loam or laterite soils with a pH range of 5.5 - 8.0 are suitable.', 'Seed nuts or seedlings', 'Pits of size 1 m x 1 m x 1 m are dug and filled with topsoil and 10 kg of FYM. Plant the seed nuts or seedlings at a spacing of 7.5 m x 7.5 m.', 'Irrigate the plants immediately after planting and thereafter, irrigate once in 3 days for the first month and once in a week thereafter.', 'Apply FYM 50 kg, neem cake 2 kg, neem oil 400 ml, Azospirillum 1 kg and Phosphobacteria 1 kg per plant per year.', 'Remove the weeds and provide drainage in the basins.', 'Green gram or black gram can be grown as intercrop during the initial years of planting.', '5 - 6 years after planting, The crop can be harvested throughout the year.', 'Apply N, P and K at the rate of 500, 200 and 500 g per plant in June, September and January.', 'Remove the weeds and provide drainage in the basins.', 'Apply zinc sulphate and magnesium sulphate at the rate of 50 g each per plant per year.', 'Regular pruning should be done to remove water sprouts, dead and diseased branches.', 'The trees can be trained to a single stem or multistem.', 'June - July and November - December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The micronutrients like zinc, copper, iron and manganese should be applied based on soil and leaf analysis.', 'The soil around the basin should be worked to remove weeds and to facilitate aeration.', '', '', '', '', ''),
('6', 'Apple', 'Malus domestica Borkh.', 'Rosaceae', 'apple.png', 'Red Delicious, Golden Delicious, Tydeman\'s Early Worcester, etc.', 'Well-drained, loamy soil with a pH range of 6.0 - 7.5 is ideal.', 'Grafted plants', 'Prepare pits of size 1 m x 1 m x 1 m and fill them with topsoil and 10 kg of FYM. Plant the grafted plants at a spacing of 6 m x 6 m.', 'Irrigate immediately after planting and thereafter, irrigate once in 3 days for the first month and then once a week.', 'Apply FYM 50 kg, neem cake 2 kg, neem oil 400 ml, Azospirillum 1 kg and Phosphobacteria 1 kg per plant per year.', 'Remove the weeds and provide drainage.', 'Inter-row crops like beans, peas or carrots can be grown during the initial years.', '4 - 5 years after planting, The crop can be harvested once a year.', 'Apply N, P and K at the rate of 500, 200 and 200 g per plant in June, September and January.', 'Remove the weeds and provide drainage.', 'Apply zinc sulphate and magnesium sulphate at the rate of 50 g each per plant per year.', 'Pruning should be done annually to remove water sprouts, dead and diseased branches.', 'The trees should be trained to a modified central leader system.', 'Flowering can be induced by spraying 200 ppm GA3 solution during the dormant season.', 'June - July and November - December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The micronutrients like zinc, copper, iron and manganese should be applied based on soil and leaf analysis.', 'The soil around the basin should be worked to remove weeds and to facilitate aeration.', '', '', '', ''),
('8', 'Rice', 'Oryza sativa L.', 'Poaceae', 'rice.png', 'Samba Mahsuri, IR 64, MTU 1010, etc.', 'Loamy or clayey soils with good water retention capacity are ideal. Soil pH should be in the range of 5.0 - 7.0.', 'Seeds or seedlings', 'Prepare the field by plowing and harrowing. Incorporate 10 tonnes of FYM per hectare before the final plowing. Apply 50 kg N, 25 kg P2O5 and 25 kg K2O per hectare as basal dose. Apply lime as per soil test recommendations.', 'Transplant the seedlings in puddled field. Maintain standing water in the field up to a depth of 2 - 5 cm during the vegetative phase and 10 - 15 cm during the reproductive phase.', 'Apply N 25 kg and K2O 25 kg per hectare at maximum tillering and P2O5 25 kg per hectare at panicle initiation stage.', 'Regular weeding and top dressing of urea at the rate of 25 kg per hectare at maximum tillering and 25 days after first dose of urea.', 'Sesame or greengram can be grown as intercrop during the early stages of crop growth.', '120 - 150 days after transplanting, The crop can be harvested.', 'Spray 0.1% quinalphos or chlorpyriphos to control stem borers and leaf folder.', 'Direct seeding or transplanting is done in rows spaced at 20 cm with a plant to plant spacing of 10 cm.', 'Regular removal of weeds from the field is necessary to reduce competition for nutrients and water.', 'Pruning of rice plants is not necessary.', 'No specific top working practices are required for rice.', 'Spray 200 ppm ethrel to induce flowering and reduce lodging.', 'June - July and November - December, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and hoeing should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular drainage of excess water from the field should be ensured to prevent waterlogging.', '', ''),
('9', 'Wheat', 'Triticum aestivum L.', 'Poaceae', 'wheat.png', 'HD 2967, PBW 502, UP 2526, etc.', 'Well-drained loamy soils with good fertility are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds', 'Prepare the field by plowing and harrowing. Apply 120 kg of nitrogen, 60 kg of phosphorus, and 40 kg of potassium per hectare as basal dose along with 25 kg of zinc sulphate.', 'Sow the seeds at a depth of 5 - 7 cm in rows spaced at 22.5 cm apart.', 'Apply nitrogen at the rate of 60 kg per hectare at crown root initiation stage and remaining 60 kg at jointing stage.', 'Regular weeding and thinning should be done to maintain proper plant population and reduce competition.', 'Leguminous crops like lentils or chickpeas can be grown as intercrop during the winter season.', '120 - 150 days after sowing, The crop can be harvested.', 'Spray 0.2% imidacloprid or thiamethoxam to control aphids and whiteflies.', 'Seeds should be sown using a seed drill or broadcasting method.', 'Regular removal of weeds is essential to reduce competition for nutrients and water.', 'No specific pruning practices are required for wheat.', 'No specific top working practices are required for wheat.', 'Application of gibberellic acid can be done to improve grain size and quality.', 'November - December and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and hoeing should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('10', 'Sugarcane', 'Saccharum officinarum L.', 'Poaceae', 'sugercane.png', 'Co 86032, Co 0238, Co 0301, etc.', 'Sandy loam or clay loam soils with good drainage and high organic matter content are ideal. Soil pH should be in the range of 6.5 - 8.5.', 'Setts', 'Prepare the field by plowing and harrowing. Apply 200 kg of nitrogen, 100 kg of phosphorus, and 100 kg of potassium per hectare as basal dose along with 25 kg of zinc sulphate and 25 kg of magnesium sulphate.', 'Plant the setts in furrows at a depth of 5 - 7 cm with a spacing of 75 cm x 30 cm.', 'Apply nitrogen at the rate of 100 kg per hectare at 30 and 60 days after planting.', 'Regular earthing up and removal of weeds should be done to maintain soil moisture and reduce competition.', 'Leguminous crops like black gram or green gram can be grown as intercrop during the initial stages of crop growth.', '10 - 12 months after planting, The crop can be harvested.', 'Spray 0.05% monocrotophos or chlorpyriphos to control early shoot borer and stem borer.', 'Setts should be planted in furrows using a mechanical planter or manually.', 'Regular removal of weeds from the inter-rows is essential to reduce competition.', 'No specific pruning practices are required for sugarcane.', 'No specific top working practices are required for sugarcane.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'May - June and September - October, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular earthing up and weeding should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('11', 'Potato', 'Solanum tuberosum L.', 'Solanaceae', 'potato.png', 'Kufri Jyoti, Kufri Pukhraj, Kufri Chandramukhi, etc.', 'Well-drained sandy loam soils with good organic matter content are ideal. Soil pH should be in the range of 5.0 - 7.0.', 'Tubers', 'Prepare ridges and furrows with a spacing of 60 cm x 15 cm. Apply 10 tonnes of FYM per hectare as basal dose along with 100 kg of nitrogen, 80 kg of phosphorus, and 120 kg of potassium.', 'Plant the seed tubers in the furrows at a depth of 5 - 7 cm.', 'Apply nitrogen at the rate of 50 kg per hectare at planting and the remaining 50 kg at hilling.', 'Regular hilling up and removal of weeds should be done to prevent tuber exposure and reduce competition.', 'Leguminous crops like peas or beans can be grown as intercrop during the early stages of crop growth.', '90 - 120 days after planting, The crop can be harvested.', 'Spray 0.05% monocrotophos or chlorpyriphos to control potato tuber moth.', 'Seed tubers should be planted in furrows using a mechanical planter or manually.', 'Regular removal of weeds from the ridges and furrows is essential to reduce competition.', 'No specific pruning practices are required for potato.', 'No specific top working practices are required for potato.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'February - March and July - August, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular hilling up and weeding should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('12', 'Onion', 'Allium cepa L.', 'Amaryllidaceae', 'onion.png', 'Nasik Red, Pusa Red, Agrifound Dark Red, etc.', 'Sandy loam or clay loam soils with good drainage and high organic matter content are suitable. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds or bulbs', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds or transplant the bulbs at a spacing of 10 cm x 10 cm.', 'Irrigate immediately after planting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of planting and the remaining N in 2 equal splits at 30 and 60 days after planting.', 'Keep the field weed free and provide support for the plants using stakes or strings.', 'Inter-row crops like coriander or spinach can be grown during the early stages of growth.', '90 - 120 days after planting, The crop can be harvested.', 'Spray 0.2% malathion or carbaryl to control onion thrips and leaf miners.', 'Seeds should be sown at a depth of 1 - 2 cm using a seed drill or broadcasting method.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for onion.', 'No specific top working practices are required for onion.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and thinning should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('13', 'Tomato', 'Solanum lycopersicum L.', 'Solanaceae', 'tomato.png', 'Arka Vikas, Arka Rakshak, Arka Meghali, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 60 cm x 45 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'Inter-row crops like marigold or basil can be grown to attract beneficial insects.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'No specific top working practices are required for tomato.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('14', 'Brinjal', 'Solanum melongena L.', 'Solanaceae', 'brinjal.png', 'Pusa Purple Long, Black Beauty, Arka Keshav, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 5.5 - 7.5.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 60 cm x 60 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'Inter-row crops like marigold or basil can be grown to attract beneficial insects.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'No specific top working practices are required for brinjal.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('15', 'Cabbage', 'Brassica oleracea L. var. capitata', 'Brassicaceae', 'cabbage.png', 'Golden Acre, Early Drumhead, Danish Ballhead, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 45 cm x 45 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'Inter-row crops like lettuce or spinach can be grown during the early stages of crop growth.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control cabbage butterflies and aphids.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'No specific top working practices are required for cabbage.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per-hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('16', 'Cauliflower', 'Brassica oleracea L. var. botrytis', 'Brassicaceae', 'Cauliflower.png', 'Snowball 16, Pusa Snowball K-1, Pusa Hybrid 4, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 60 cm x 60 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'Inter-row crops like lettuce or spinach can be grown during the early stages of crop growth.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control cauliflower butterflies and aphids.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'No specific top working practices are required for cauliflower.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('17', 'Carrot', 'Daucus carota L. subsp. sativus', 'Apiaceae', 'carrot.png', 'Nantes, Danvers Half Long, Imperator, etc.', 'Sandy loam or loamy soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds directly in the beds at a spacing of 30 cm x 10 cm.', 'Irrigate immediately after sowing and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing and the remaining N in 2 equal splits at 30 and 60 days after sowing.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Leguminous crops like peas or beans can be grown as intercrop during the early stages of crop growth.', '90 - 120 days after sowing, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seeds should be sown directly into the prepared beds using a seed drill or broadcasting method.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for carrot.', 'No specific top working practices are required for carrot.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('18', 'Spinach', 'Spinacia oleracea L.', 'Amaranthaceae', 'spinach.png', 'All Green, Palak 143, New Zealand, etc.', 'Loamy soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds directly in the beds at a spacing of 10 cm x 10 cm.', 'Irrigate immediately after sowing and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing and the remaining N in 2 equal splits at 30 and 60 days after sowing.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Leguminous crops like peas or beans can be grown as intercrop during the early stages of crop growth.', '30 - 45 days after sowing, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control leaf miners and aphids.', 'Seeds should be sown directly into the prepared beds using a seed drill or broadcasting method.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for spinach.', 'No specific top working practices are required for spinach.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('19', 'Cucumber', 'Cucumis sativus L.', 'Cucurbitaceae', 'cucumber.png', 'Pusa Nasdar, Poinsette, Beth Alpha, etc.', 'Sandy loam soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds or seedlings', 'Prepare ridges and furrows with a spacing of 2 m x 0.5 m. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds or transplant the seedlings at a spacing of 60 cm x 45 cm.', 'Irrigate immediately after sowing or transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing or transplanting and the remaining N in 2 equal splits at 30 and 60 days after sowing or transplanting.', 'Regular pruning of lateral branches and removal of damaged leaves should be done to promote proper growth and fruiting.', 'Inter-row crops like radish or onion can be grown during the early stages of crop growth.', '50 - 60 days after sowing or transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seeds should be sown directly into the prepared ridges using a seed drill or broadcasting method. Seedlings can be transplanted using a dibbler or by hand.', 'Regular removal of weeds from the ridges and furrows is essential to reduce competition.', 'Pruning of lateral branches and removal of damaged leaves should be done to promote proper growth and fruiting.', 'No specific top working practices are required for cucumber.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the ridges and furrows weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('20', 'Lettuce', 'Lactuca sativa L.', 'Asteraceae', 'Lettuce.png', 'Iceberg, Romaine, Butterhead, etc.', 'Loamy soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds or transplant the seedlings at a spacing of 30 cm x 30 cm.', 'Irrigate immediately after sowing or transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing or transplanting and the remaining N in 2 equal splits at 30 and 60 days after sowing or transplanting.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Inter-row crops like radish or carrot can be grown during the early stages of crop growth.', '45 - 60 days after sowing or transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seeds should be sown directly into the prepared beds using a seed drill or broadcasting method. Seedlings can be transplanted using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for lettuce.', 'No specific top working practices are required for lettuce.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('24', 'Sweet Potato', 'Ipomoea batatas (L.) Lam.', 'Convolvulaceae', 'sweet potato.png', 'CO1, CO2, CO3, etc.', 'Well-drained sandy loam soils rich in organic matter are ideal. Soil pH should be in the range of 5.5 - 6.5.', 'Vine cuttings', 'Prepare ridges and furrows with a spacing of 75 cm x 30 cm. Apply 20 tonnes of FYM per hectare before the last plowing. Plant the vine cuttings in the furrows at a spacing of 30 cm x 30 cm.', 'Irrigate immediately after planting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of planting and the remaining N in 2 equal splits at 30 and 60 days after planting.', 'Regular hilling or earthing up should be done to protect the emerging shoots and tubers from sunlight.', 'Inter-row crops like legumes or leafy vegetables can be grown during the early stages of crop growth.', '120 - 150 days after planting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control sweet potato weevils and whiteflies.', 'Vine cuttings should be planted in the prepared furrows at a spacing of 30 cm x 30 cm.', 'Regular hilling or earthing up should be done to protect the emerging shoots and tubers from sunlight.', 'No specific top working practices are required for sweet potato.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the ridges and furrows weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', '', ''),
('30', 'Radish', 'Raphanus sativus L.', 'Brassicaceae', 'radish.png', 'Pusa Reshmi, Pusa Himani, Japanese White, etc.', 'Well-drained sandy loam soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds thinly in rows with a spacing of 15 cm x 10 cm.', 'Irrigate immediately after sowing and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 60 kg, P2O5 30 kg and K2O 30 kg per hectare at the time of sowing.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Inter-row crops like lettuce or spinach can be grown during the early stages of crop growth.', '30 - 40 days after sowing, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and caterpillars.', 'Seeds should be sown thinly in rows on the prepared raised beds with a spacing of 15 cm x 10 cm.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for radish.', 'No specific top working practices are required for radish.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('2', 'Banana', 'Musa spp.', 'Musaceae', 'banana.png', 'Rasbale', 'Sandy loam soils with good drainage are ideal. It can tolerate a pH range of 6.0 - 7.5.', 'Tissue culture plants or suckers', 'Dig pits of 60 cm x 60 cm x 60 cm size and fill it up with topsoil mixed with 10 kg of FYM and 100 g of neem cake. Plant the suckers at a spacing of 1.8 m x 1.8 m.', 'Immediately after planting and thereafter once in three days till establishment.', 'Apply 25 kg FYM, 100 g N, 40 g P2O5 and 140 g K2O per plant, three times a year in June, September and December.', 'Regular weeding and earthing up at 2 months interval.', 'Beans or bhendi can be grown as intercrop for the first 2 - 3 years.', '8 - 10 months after planting, 3 - 4 bunches/plant', 'Stem borer: Inserting a cloth wrapped stiff wire into the tunnel and killing the larva; Keep the field free from weeds and trash.', 'Planting is done in pits of 60 cm x 60 cm x 60 cm size filled with topsoil mixed with 10 kg of FYM and 100 g of neem cake.', 'Spacing of 1.8 m x 1.8 m is followed.', 'The planting material should be planted in rows with a spacing of 1.8 m between rows.', 'The top portion of the pseudostem can be cut and the leaves should be removed 15 days before planting.', 'Regular inspection and removal of male buds, dead flowers and old leaves.', 'First dose of fertilizer is applied three months after planting and the second dose six months after planting.', 'Removing the male buds and de-suckering are done after the bunch harvest.', 'After each harvest, the plant debris should be removed and destroyed.', 'Mulching with straw or dry leaves is done to conserve moisture and control weeds.', '', '', ''),
('3', 'Acid Lime', 'Citrus aurantifolia Swingle', 'Rutaceae', 'lemon.png', 'Local - Mexican lime', 'Requires well drained soils with a pH range of 5.5 - 7.5.', 'Budded plants or cuttings', 'Preparing pits of size 60 cm x 60 cm x 60 cm and filling them with 10 kg of FYM mixed with 500 g of neem cake. Planting the budded plants or cuttings at a spacing of 5 m x 5 m.', 'After planting, water the plants daily for the first 15 days, then once in 3 days till one month and thereafter, once in a week.', 'Apply FYM 25 kg, Neem cake 1 kg, Neem oil 200 ml, Azospirillum 500 g and Phosphobacteria 500 g per plant/year.', 'Remove the weeds and keep the basins weed free.', 'Short duration vegetables like radish, carrot, coriander, bhendi or beans can be grown as intercrops during the initial years.', '3 - 4 years after planting, The crop can be harvested 2 - 3 times a year.', 'Apply N, P and K at the rate of 500, 200 and 100 g per plant in June, October and February.', 'Provide one or two hoeing and weeding every year.', 'Apply lime and magnesium as per soil test recommendations.', 'Pruning should be done 2 - 3 times in a year to avoid overcrowding of branches and to remove water sprouts.', 'Off season flowering can be induced by applying 3% KNO3 solution at the rate of 50 ml/plant.', 'June – July and November – December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The application of micronutrients like zinc, copper, iron and manganese should be done based on soil and leaf analysis.', 'The soil in the basins should be worked to remove weeds and dead leaves, and to prevent water stagnation.', '', '', '', '', ''),
('4', 'Sweet Orange', 'Citrus sinensis (L.) Osbeck', 'Rutaceae', 'sweet-orange.png', 'Nucellar seedlings (Local - Khasi)', 'A well-drained, fertile soil with a pH range of 5.5 - 7.5 is ideal. The crop can tolerate slightly alkaline soils.', 'Budded plants', 'Dig pits of size 90 cm x 90 cm x 90 cm and fill them up with 15 kg of FYM and 500 g of neem cake. Plant the budded plants at a spacing of 7.5 m x 7.5 m.', 'For the first 15 days after planting, water the plants daily and then irrigate once in 3 days till one month and thereafter, irrigate once a week.', 'Apply FYM 50 kg, neem cake 2 kg, neem oil 400 ml, Azospirillum 1 kg and Phosphobacteria 1 kg per plant per year.', 'Keep the basin weed free and provide drainage.', 'Dhaincha or cowpea can be grown as intercrop during the initial years of planting.', 'The crop starts bearing 5 - 6 years after planting and the yield increases with the age of the plant.', 'Apply N, P and K at the rate of 600, 300 and 300 g per plant in June, September and January.', 'The soil around the basin should be worked to remove weeds and to facilitate aeration.', 'Apply zinc sulphate and magnesium sulphate at the rate of 50 g each per plant per year.', 'Regular pruning should be done to remove water sprouts, dead and diseased branches.', 'Flowering and fruiting can be induced by spraying 200 ppm Ethrel during December - January.', 'June - July and November - December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The micronutrients like zinc, copper, iron and manganese should be applied based on soil and leaf analysis.', 'A light irrigation should be given to the plants just before the onset of monsoon to facilitate uniform and better growth.', '', '', '', '', ''),
('5', 'Coconut', 'Cocos nucifera L.', 'Arecaceae', 'coconut.png', 'Tall, Dwarf, Hybrid varieties', 'Sandy loam or laterite soils with a pH range of 5.5 - 8.0 are suitable.', 'Seed nuts or seedlings', 'Pits of size 1 m x 1 m x 1 m are dug and filled with topsoil and 10 kg of FYM. Plant the seed nuts or seedlings at a spacing of 7.5 m x 7.5 m.', 'Irrigate the plants immediately after planting and thereafter, irrigate once in 3 days for the first month and once in a week thereafter.', 'Apply FYM 50 kg, neem cake 2 kg, neem oil 400 ml, Azospirillum 1 kg and Phosphobacteria 1 kg per plant per year.', 'Remove the weeds and provide drainage in the basins.', 'Green gram or black gram can be grown as intercrop during the initial years of planting.', '5 - 6 years after planting, The crop can be harvested throughout the year.', 'Apply N, P and K at the rate of 500, 200 and 500 g per plant in June, September and January.', 'Remove the weeds and provide drainage in the basins.', 'Apply zinc sulphate and magnesium sulphate at the rate of 50 g each per plant per year.', 'Regular pruning should be done to remove water sprouts, dead and diseased branches.', 'The trees can be trained to a single stem or multistem.', 'June - July and November - December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The micronutrients like zinc, copper, iron and manganese should be applied based on soil and leaf analysis.', 'The soil around the basin should be worked to remove weeds and to facilitate aeration.', '', '', '', '', ''),
('6', 'Apple', 'Malus domestica Borkh.', 'Rosaceae', 'apple.png', 'Red Delicious, Golden Delicious, Tydeman\'s Early Worcester, etc.', 'Well-drained, loamy soil with a pH range of 6.0 - 7.5 is ideal.', 'Grafted plants', 'Prepare pits of size 1 m x 1 m x 1 m and fill them with topsoil and 10 kg of FYM. Plant the grafted plants at a spacing of 6 m x 6 m.', 'Irrigate immediately after planting and thereafter, irrigate once in 3 days for the first month and then once a week.', 'Apply FYM 50 kg, neem cake 2 kg, neem oil 400 ml, Azospirillum 1 kg and Phosphobacteria 1 kg per plant per year.', 'Remove the weeds and provide drainage.', 'Inter-row crops like beans, peas or carrots can be grown during the initial years.', '4 - 5 years after planting, The crop can be harvested once a year.', 'Apply N, P and K at the rate of 500, 200 and 200 g per plant in June, September and January.', 'Remove the weeds and provide drainage.', 'Apply zinc sulphate and magnesium sulphate at the rate of 50 g each per plant per year.', 'Pruning should be done annually to remove water sprouts, dead and diseased branches.', 'The trees should be trained to a modified central leader system.', 'Flowering can be induced by spraying 200 ppm GA3 solution during the dormant season.', 'June - July and November - December, Apply 200 g of Azospirillum and Phosphobacteria per plant.', 'The micronutrients like zinc, copper, iron and manganese should be applied based on soil and leaf analysis.', 'The soil around the basin should be worked to remove weeds and to facilitate aeration.', '', '', '', ''),
('8', 'Rice', 'Oryza sativa L.', 'Poaceae', 'rice.png', 'Samba Mahsuri, IR 64, MTU 1010, etc.', 'Loamy or clayey soils with good water retention capacity are ideal. Soil pH should be in the range of 5.0 - 7.0.', 'Seeds or seedlings', 'Prepare the field by plowing and harrowing. Incorporate 10 tonnes of FYM per hectare before the final plowing. Apply 50 kg N, 25 kg P2O5 and 25 kg K2O per hectare as basal dose. Apply lime as per soil test recommendations.', 'Transplant the seedlings in puddled field. Maintain standing water in the field up to a depth of 2 - 5 cm during the vegetative phase and 10 - 15 cm during the reproductive phase.', 'Apply N 25 kg and K2O 25 kg per hectare at maximum tillering and P2O5 25 kg per hectare at panicle initiation stage.', 'Regular weeding and top dressing of urea at the rate of 25 kg per hectare at maximum tillering and 25 days after first dose of urea.', 'Sesame or greengram can be grown as intercrop during the early stages of crop growth.', '120 - 150 days after transplanting, The crop can be harvested.', 'Spray 0.1% quinalphos or chlorpyriphos to control stem borers and leaf folder.', 'Direct seeding or transplanting is done in rows spaced at 20 cm with a plant to plant spacing of 10 cm.', 'Regular removal of weeds from the field is necessary to reduce competition for nutrients and water.', 'Pruning of rice plants is not necessary.', 'No specific top working practices are required for rice.', 'Spray 200 ppm ethrel to induce flowering and reduce lodging.', 'June - July and November - December, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and hoeing should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular drainage of excess water from the field should be ensured to prevent waterlogging.', '', ''),
('9', 'Wheat', 'Triticum aestivum L.', 'Poaceae', 'wheat.png', 'HD 2967, PBW 502, UP 2526, etc.', 'Well-drained loamy soils with good fertility are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds', 'Prepare the field by plowing and harrowing. Apply 120 kg of nitrogen, 60 kg of phosphorus, and 40 kg of potassium per hectare as basal dose along with 25 kg of zinc sulphate.', 'Sow the seeds at a depth of 5 - 7 cm in rows spaced at 22.5 cm apart.', 'Apply nitrogen at the rate of 60 kg per hectare at crown root initiation stage and remaining 60 kg at jointing stage.', 'Regular weeding and thinning should be done to maintain proper plant population and reduce competition.', 'Leguminous crops like lentils or chickpeas can be grown as intercrop during the winter season.', '120 - 150 days after sowing, The crop can be harvested.', 'Spray 0.2% imidacloprid or thiamethoxam to control aphids and whiteflies.', 'Seeds should be sown using a seed drill or broadcasting method.', 'Regular removal of weeds is essential to reduce competition for nutrients and water.', 'No specific pruning practices are required for wheat.', 'No specific top working practices are required for wheat.', 'Application of gibberellic acid can be done to improve grain size and quality.', 'November - December and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and hoeing should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', '');
INSERT INTO `crop_library` (`id`, `plant_name`, `scientific_name`, `family`, `image`, `varieties`, `soil_and_climate`, `planting_material`, `field_preparation`, `irrigation`, `manures_and_fertilizers`, `after_cultivation`, `intercropping`, `harvest`, `yield`, `pest_management`, `planting`, `spacing`, `canopy_management`, `top_working`, `growth_regulators`, `off_season_crop_induction`, `Season_of_Planting`, `Application_of_Fertilizers`, `Aftercultivation`, `Micronutrients`, `Special_Practices`) VALUES
('10', 'Sugarcane', 'Saccharum officinarum L.', 'Poaceae', 'sugercane.png', 'Co 86032, Co 0238, Co 0301, etc.', 'Sandy loam or clay loam soils with good drainage and high organic matter content are ideal. Soil pH should be in the range of 6.5 - 8.5.', 'Setts', 'Prepare the field by plowing and harrowing. Apply 200 kg of nitrogen, 100 kg of phosphorus, and 100 kg of potassium per hectare as basal dose along with 25 kg of zinc sulphate and 25 kg of magnesium sulphate.', 'Plant the setts in furrows at a depth of 5 - 7 cm with a spacing of 75 cm x 30 cm.', 'Apply nitrogen at the rate of 100 kg per hectare at 30 and 60 days after planting.', 'Regular earthing up and removal of weeds should be done to maintain soil moisture and reduce competition.', 'Leguminous crops like black gram or green gram can be grown as intercrop during the initial stages of crop growth.', '10 - 12 months after planting, The crop can be harvested.', 'Spray 0.05% monocrotophos or chlorpyriphos to control early shoot borer and stem borer.', 'Setts should be planted in furrows using a mechanical planter or manually.', 'Regular removal of weeds from the inter-rows is essential to reduce competition.', 'No specific pruning practices are required for sugarcane.', 'No specific top working practices are required for sugarcane.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'May - June and September - October, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular earthing up and weeding should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('11', 'Potato', 'Solanum tuberosum L.', 'Solanaceae', 'potato.png', 'Kufri Jyoti, Kufri Pukhraj, Kufri Chandramukhi, etc.', 'Well-drained sandy loam soils with good organic matter content are ideal. Soil pH should be in the range of 5.0 - 7.0.', 'Tubers', 'Prepare ridges and furrows with a spacing of 60 cm x 15 cm. Apply 10 tonnes of FYM per hectare as basal dose along with 100 kg of nitrogen, 80 kg of phosphorus, and 120 kg of potassium.', 'Plant the seed tubers in the furrows at a depth of 5 - 7 cm.', 'Apply nitrogen at the rate of 50 kg per hectare at planting and the remaining 50 kg at hilling.', 'Regular hilling up and removal of weeds should be done to prevent tuber exposure and reduce competition.', 'Leguminous crops like peas or beans can be grown as intercrop during the early stages of crop growth.', '90 - 120 days after planting, The crop can be harvested.', 'Spray 0.05% monocrotophos or chlorpyriphos to control potato tuber moth.', 'Seed tubers should be planted in furrows using a mechanical planter or manually.', 'Regular removal of weeds from the ridges and furrows is essential to reduce competition.', 'No specific pruning practices are required for potato.', 'No specific top working practices are required for potato.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'February - March and July - August, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular hilling up and weeding should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('12', 'Onion', 'Allium cepa L.', 'Amaryllidaceae', 'onion.png', 'Nasik Red, Pusa Red, Agrifound Dark Red, etc.', 'Sandy loam or clay loam soils with good drainage and high organic matter content are suitable. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds or bulbs', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds or transplant the bulbs at a spacing of 10 cm x 10 cm.', 'Irrigate immediately after planting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of planting and the remaining N in 2 equal splits at 30 and 60 days after planting.', 'Keep the field weed free and provide support for the plants using stakes or strings.', 'Inter-row crops like coriander or spinach can be grown during the early stages of growth.', '90 - 120 days after planting, The crop can be harvested.', 'Spray 0.2% malathion or carbaryl to control onion thrips and leaf miners.', 'Seeds should be sown at a depth of 1 - 2 cm using a seed drill or broadcasting method.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for onion.', 'No specific top working practices are required for onion.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and thinning should be done to keep the field weed free.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('13', 'Tomato', 'Solanum lycopersicum L.', 'Solanaceae', 'tomato.png', 'Arka Vikas, Arka Rakshak, Arka Meghali, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 60 cm x 45 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'Inter-row crops like marigold or basil can be grown to attract beneficial insects.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'No specific top working practices are required for tomato.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('14', 'Brinjal', 'Solanum melongena L.', 'Solanaceae', 'brinjal.png', 'Pusa Purple Long, Black Beauty, Arka Keshav, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 5.5 - 7.5.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 60 cm x 60 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'Inter-row crops like marigold or basil can be grown to attract beneficial insects.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lateral branches and removal of suckers should be done to promote proper growth and fruiting.', 'No specific top working practices are required for brinjal.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('15', 'Cabbage', 'Brassica oleracea L. var. capitata', 'Brassicaceae', 'cabbage.png', 'Golden Acre, Early Drumhead, Danish Ballhead, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 45 cm x 45 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'Inter-row crops like lettuce or spinach can be grown during the early stages of crop growth.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control cabbage butterflies and aphids.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'No specific top working practices are required for cabbage.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per-hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('16', 'Cauliflower', 'Brassica oleracea L. var. botrytis', 'Brassicaceae', 'Cauliflower.png', 'Snowball 16, Pusa Snowball K-1, Pusa Hybrid 4, etc.', 'Well-drained loamy soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Transplant the seedlings at a spacing of 60 cm x 60 cm.', 'Irrigate immediately after transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of transplanting and the remaining N in 2 equal splits at 30 and 60 days after transplanting.', 'Regular pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'Inter-row crops like lettuce or spinach can be grown during the early stages of crop growth.', '90 - 120 days after transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control cauliflower butterflies and aphids.', 'Seedlings should be transplanted into the prepared beds using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'Pruning of lower leaves and removal of damaged leaves should be done to promote proper head formation.', 'No specific top working practices are required for cauliflower.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('17', 'Carrot', 'Daucus carota L. subsp. sativus', 'Apiaceae', 'carrot.png', 'Nantes, Danvers Half Long, Imperator, etc.', 'Sandy loam or loamy soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds directly in the beds at a spacing of 30 cm x 10 cm.', 'Irrigate immediately after sowing and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing and the remaining N in 2 equal splits at 30 and 60 days after sowing.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Leguminous crops like peas or beans can be grown as intercrop during the early stages of crop growth.', '90 - 120 days after sowing, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seeds should be sown directly into the prepared beds using a seed drill or broadcasting method.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for carrot.', 'No specific top working practices are required for carrot.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('18', 'Spinach', 'Spinacia oleracea L.', 'Amaranthaceae', 'spinach.png', 'All Green, Palak 143, New Zealand, etc.', 'Loamy soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds directly in the beds at a spacing of 10 cm x 10 cm.', 'Irrigate immediately after sowing and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing and the remaining N in 2 equal splits at 30 and 60 days after sowing.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Leguminous crops like peas or beans can be grown as intercrop during the early stages of crop growth.', '30 - 45 days after sowing, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control leaf miners and aphids.', 'Seeds should be sown directly into the prepared beds using a seed drill or broadcasting method.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for spinach.', 'No specific top working practices are required for spinach.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('19', 'Cucumber', 'Cucumis sativus L.', 'Cucurbitaceae', 'cucumber.png', 'Pusa Nasdar, Poinsette, Beth Alpha, etc.', 'Sandy loam soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds or seedlings', 'Prepare ridges and furrows with a spacing of 2 m x 0.5 m. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds or transplant the seedlings at a spacing of 60 cm x 45 cm.', 'Irrigate immediately after sowing or transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing or transplanting and the remaining N in 2 equal splits at 30 and 60 days after sowing or transplanting.', 'Regular pruning of lateral branches and removal of damaged leaves should be done to promote proper growth and fruiting.', 'Inter-row crops like radish or onion can be grown during the early stages of crop growth.', '50 - 60 days after sowing or transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seeds should be sown directly into the prepared ridges using a seed drill or broadcasting method. Seedlings can be transplanted using a dibbler or by hand.', 'Regular removal of weeds from the ridges and furrows is essential to reduce competition.', 'Pruning of lateral branches and removal of damaged leaves should be done to promote proper growth and fruiting.', 'No specific top working practices are required for cucumber.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the ridges and furrows weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('20', 'Lettuce', 'Lactuca sativa L.', 'Asteraceae', 'Lettuce.png', 'Iceberg, Romaine, Butterhead, etc.', 'Loamy soils with good drainage are ideal. Soil pH should be in the range of 6.0 - 7.0.', 'Seeds or seedlings', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds or transplant the seedlings at a spacing of 30 cm x 30 cm.', 'Irrigate immediately after sowing or transplanting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of sowing or transplanting and the remaining N in 2 equal splits at 30 and 60 days after sowing or transplanting.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Inter-row crops like radish or carrot can be grown during the early stages of crop growth.', '45 - 60 days after sowing or transplanting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and whiteflies.', 'Seeds should be sown directly into the prepared beds using a seed drill or broadcasting method. Seedlings can be transplanted using a dibbler or by hand.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for lettuce.', 'No specific top working practices are required for lettuce.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', ''),
('24', 'Sweet Potato', 'Ipomoea batatas (L.) Lam.', 'Convolvulaceae', 'sweet potato.png', 'CO1, CO2, CO3, etc.', 'Well-drained sandy loam soils rich in organic matter are ideal. Soil pH should be in the range of 5.5 - 6.5.', 'Vine cuttings', 'Prepare ridges and furrows with a spacing of 75 cm x 30 cm. Apply 20 tonnes of FYM per hectare before the last plowing. Plant the vine cuttings in the furrows at a spacing of 30 cm x 30 cm.', 'Irrigate immediately after planting and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 120 kg, P2O5 60 kg and K2O 60 kg per hectare. Apply half of N and full dose of P and K at the time of planting and the remaining N in 2 equal splits at 30 and 60 days after planting.', 'Regular hilling or earthing up should be done to protect the emerging shoots and tubers from sunlight.', 'Inter-row crops like legumes or leafy vegetables can be grown during the early stages of crop growth.', '120 - 150 days after planting, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control sweet potato weevils and whiteflies.', 'Vine cuttings should be planted in the prepared furrows at a spacing of 30 cm x 30 cm.', 'Regular hilling or earthing up should be done to protect the emerging shoots and tubers from sunlight.', 'No specific top working practices are required for sweet potato.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the ridges and furrows weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', '', ''),
('30', 'Radish', 'Raphanus sativus L.', 'Brassicaceae', 'radish.png', 'Pusa Reshmi, Pusa Himani, Japanese White, etc.', 'Well-drained sandy loam soils rich in organic matter are ideal. Soil pH should be in the range of 6.0 - 7.5.', 'Seeds', 'Prepare raised beds of 1 m width and convenient length. Apply 20 tonnes of FYM per hectare before the last plowing. Sow the seeds thinly in rows with a spacing of 15 cm x 10 cm.', 'Irrigate immediately after sowing and thereafter, irrigate once in 2 days for the first week and then once a week.', 'Apply FYM 20 tonnes, N 60 kg, P2O5 30 kg and K2O 30 kg per hectare at the time of sowing.', 'Regular thinning should be done to maintain proper plant spacing and reduce competition.', 'Inter-row crops like lettuce or spinach can be grown during the early stages of crop growth.', '30 - 40 days after sowing, The crop can be harvested.', 'Spray 0.05% neem oil or 0.1% azadirachtin to control aphids and caterpillars.', 'Seeds should be sown thinly in rows on the prepared raised beds with a spacing of 15 cm x 10 cm.', 'Regular removal of weeds from the beds is essential to reduce competition.', 'No specific pruning practices are required for radish.', 'No specific top working practices are required for radish.', 'Application of 2,4-D at the rate of 2 kg per hectare can be done to control weeds.', 'October - November and February - March, Apply 25 kg of Azospirillum and Phosphobacteria per hectare.', 'Regular monitoring for pests and diseases is essential.', 'Regular weeding and mulching should be done to keep the beds weed free and conserve moisture.', 'Application of micronutrients like zinc, boron, iron and manganese should be done as per soil test recommendations.', 'Regular irrigation should be provided during the critical growth stages to ensure optimum yield.', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `gardens`
--

CREATE TABLE `gardens` (
  `garden_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `garden_name` varchar(255) NOT NULL,
  `garden_size` decimal(10,2) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `creation_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `layout`
--

CREATE TABLE `layout` (
  `layout_id` int(11) NOT NULL,
  `garden_id` int(11) DEFAULT NULL,
  `item_type` enum('plant','pot') NOT NULL,
  `item_id` int(11) DEFAULT NULL,
  `x_position` decimal(10,2) DEFAULT NULL,
  `y_position` decimal(10,2) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `plants`
--

CREATE TABLE `plants` (
  `plant_id` int(11) NOT NULL,
  `garden_id` int(11) DEFAULT NULL,
  `plant_name` varchar(255) NOT NULL,
  `variety` varchar(255) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `planting_location` varchar(255) DEFAULT NULL,
  `planting_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `pots`
--

CREATE TABLE `pots` (
  `pot_id` int(11) NOT NULL,
  `garden_id` int(11) DEFAULT NULL,
  `pot_size` varchar(50) DEFAULT NULL,
  `shape` varchar(50) DEFAULT NULL,
  `material` varchar(50) DEFAULT NULL,
  `capacity` decimal(10,2) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `soilclimate`
--

CREATE TABLE `soilclimate` (
  `plant_id` int(11) NOT NULL,
  `soil_type` varchar(100) DEFAULT NULL,
  `climatic_conditions` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `f_name` varchar(255) NOT NULL,
  `l_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `dob` date DEFAULT NULL,
  `profile_photo` varchar(255) DEFAULT NULL,
  `phone_no` varchar(20) DEFAULT NULL,
  `language` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `role` varchar(5) NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `f_name`, `l_name`, `email`, `password`, `dob`, `profile_photo`, `phone_no`, `language`, `country`, `created_at`, `role`) VALUES
(2, 'pankaj', 'kumar', 'admin@test.com', 'admintest', NULL, NULL, NULL, NULL, NULL, '2024-04-30 16:32:26', 'admin');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin_users`
--
ALTER TABLE `admin_users`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `gardens`
--
ALTER TABLE `gardens`
  ADD PRIMARY KEY (`garden_id`),
  ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `layout`
--
ALTER TABLE `layout`
  ADD PRIMARY KEY (`layout_id`),
  ADD KEY `garden_id` (`garden_id`),
  ADD KEY `item_id` (`item_id`);

--
-- Indexes for table `plants`
--
ALTER TABLE `plants`
  ADD PRIMARY KEY (`plant_id`),
  ADD KEY `garden_id` (`garden_id`);

--
-- Indexes for table `pots`
--
ALTER TABLE `pots`
  ADD PRIMARY KEY (`pot_id`),
  ADD KEY `garden_id` (`garden_id`);

--
-- Indexes for table `soilclimate`
--
ALTER TABLE `soilclimate`
  ADD PRIMARY KEY (`plant_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin_users`
--
ALTER TABLE `admin_users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `gardens`
--
ALTER TABLE `gardens`
  MODIFY `garden_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `layout`
--
ALTER TABLE `layout`
  MODIFY `layout_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `plants`
--
ALTER TABLE `plants`
  MODIFY `plant_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `pots`
--
ALTER TABLE `pots`
  MODIFY `pot_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `gardens`
--
ALTER TABLE `gardens`
  ADD CONSTRAINT `gardens_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

--
-- Constraints for table `layout`
--
ALTER TABLE `layout`
  ADD CONSTRAINT `layout_ibfk_1` FOREIGN KEY (`garden_id`) REFERENCES `gardens` (`garden_id`),
  ADD CONSTRAINT `layout_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `plants` (`plant_id`) ON DELETE CASCADE;

--
-- Constraints for table `plants`
--
ALTER TABLE `plants`
  ADD CONSTRAINT `plants_ibfk_1` FOREIGN KEY (`garden_id`) REFERENCES `gardens` (`garden_id`);

--
-- Constraints for table `pots`
--
ALTER TABLE `pots`
  ADD CONSTRAINT `pots_ibfk_1` FOREIGN KEY (`garden_id`) REFERENCES `gardens` (`garden_id`);

--
-- Constraints for table `soilclimate`
--
ALTER TABLE `soilclimate`
  ADD CONSTRAINT `soilclimate_ibfk_1` FOREIGN KEY (`plant_id`) REFERENCES `plants` (`plant_id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
